INSERT INTO products_product_filters( product_filters_id,product_id) values
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='82R70091BM')),

    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='82R70091BM')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='5Y3T8EA#AKS')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='6F2M6EA#AKS')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='21K-00009')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='5BT-00009')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='NX.VVREX.003')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20XY003UBM')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20W000X1BM')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='6X927EA#AKS')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20TA00F7BM')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20WE0000BM')),

    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='1ZO-00025')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20S1S1F500')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='THJ-00046')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='21B30017BM')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='21E6006WBM')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='THJ-00047')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='1ZP-00009')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20W000TKBM')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20W400M3BM')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20X3005ABM')),

    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='SKR-00009')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20RL000GBM')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20S7S8L400')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='336D4EA#AKS')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20W4007RBM')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20VE0056BM')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='FPC04924BS')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='20TD003LBM')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='VFY:E5411MF5GRBA')),
    ((select id from product_filters where filter='Intel Core i5 (4-ядрен)'),(select id from products where code_id='VGY-00008'));