server.port=8070
management.server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5433/merchants
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.defaultSchema=public
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml
spring.liquibase.contexts=dev

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.contextPath=/api