server.port=8070
management.server.port=8092
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
spring.datasource.url=jdbc:postgresql://localhost:5433/merchants
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.datasource.schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.contextPath=/api
loki.url=http://localhost:3100/loki/api/v1/push