version: "3.9"

services:
  products-db:
    container_name: "products-db"
    image: postgres:14.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  merchants-db:
    container_name: "merchants-db"
    image: postgres:14.0
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=merchants
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  auth-db:
    container_name: "auth-db"
    image: postgres:14.0
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  images:
    image: nginx
    container_name: images
    volumes:
      - ./docker/images/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/images/images/products:/images/products
      - ./docker/images/images/merchants:/images/merchants
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  fe:
    image: nginx
    container_name: fe
    volumes:
      - ./nginx/nginx-fe.conf:/etc/nginx/nginx.conf
      - ./fe/build:/web/build
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  products:
    build: ./products
    container_name: products
    depends_on:
      - products-db
    links:
      - products-db
    environment:
      - JAR_FILE=products-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
    volumes:
      - ./products/target/products-0.0.1-SNAPSHOT.jar:/app:ro
    tty: true

  api-gateway:
    build: ./apigateway
    container_name: api-gateway
    depends_on:
      - auth-db
    links:
      - auth-db
    environment:
      - JAR_FILE=auth-0.0.1-SNAPSHOT.jar
    ports:
      - 9090:9090
    volumes:
      - ./apigateway/target/apigateway-0.0.1-SNAPSHOT.jar:/app:ro
    tty: true
