version: "3.9"

services:
  products-db:
    container_name: "products-db"
    image: postgres:14.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  images:
    image: nginx
    container_name: images
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../images:/images
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  fe:
    image: nginx
    container_name: fe
    volumes:
      - ./nginx-fe.conf:/etc/nginx/nginx.conf
      - ./fe/build:/web/build
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  products:
    build: ./products
    container_name: products
    depends_on:
      - products-db
    links:
      - products-db
    environment:
      - JAR_FILE=products-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
    volumes:
      - ./products/target/products-0.0.1-SNAPSHOT.jar:/app:ro
    tty: true