version: "3.9"

services:
  products-db:
    container_name: "products-db"
    image: postgres:14.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  merchants-db:
    container_name: "merchants-db"
    image: postgres:14.0
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=merchants
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  auth-db:
    container_name: "auth-db"
    image: postgres:14.0
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  finance-db:
    container_name: "finance-db"
    image: postgres:14.0
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=finance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  images:
    image: nginx
    container_name: images
    volumes:
      - ./docker/images/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/images/images/products:/images/products
      - ./docker/images/images/merchants:/images/merchants
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  fe:
    image: nginx
    container_name: fe
    volumes:
      - ./nginx/nginx-fe.conf:/etc/nginx/nginx.conf
      - ./fe/build:/web/build
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  products:
    build: ./products
    container_name: products
    depends_on:
      - products-db
    links:
      - products-db
    environment:
      - JAR_FILE=products-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
    volumes:
      - ./products/target/products-0.0.1-SNAPSHOT.jar:/app:ro
    tty: true

  api-gateway:
    build: ./apigateway
    container_name: api-gateway
    depends_on:
      - auth-db
    links:
      - auth-db
    environment:
      - JAR_FILE=auth-0.0.1-SNAPSHOT.jar
    ports:
      - 9090:9090
    volumes:
      - ./apigateway/target/apigateway-0.0.1-SNAPSHOT.jar:/app:ro
    tty: true

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"