spring.datasource.url=jdbc:postgresql://localhost:5432/products
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.defaultSchema=public
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml
spring.liquibase.contexts=dev

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

## Hibernate Search - Lucene indexing
spring.jpa.properties.hibernate.search.default.directory_provider=filesystem
spring.jpa.properties.hibernate.search.default.indexBase=./data/lucene

server.servlet.contextPath=/api

merchant.settings.url=http://localhost:8070/api/merchants-settings