spring.application.name=PRODUCTS
profiles.active=prod
server.servlet.contextPath=/api
server.port=8080
management.server.port=8090
management.endpoints.web.exposure.include=prometheus,health,info

# Database & Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.datasource.schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate Search - Lucene indexing
spring.jpa.properties.hibernate.search.backend.type=lucene
spring.jpa.properties.hibernate.search.backend.lucene_version=LATEST
spring.jpa.properties.hibernate.search.backend.directory.root=./lucene-index
spring.jpa.properties.hibernate.search.schema_management.strategy=create-or-update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

merchant.settings.url=${MERCHANT_SETTINGS_URL}
service.images.url=${SERVICE_IMAGES_URL}
loki.url=${LOKI_URL}

# File Uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=11MB

spring.mvc.async.request-timeout=30000

logging.pattern.level=%5p [${spring.application.name:},%X{trace_id},%X{span_id}]
otel.instrumentation.logback-appender.enabled=true