profiles.active=prod
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.defaultSchema=public
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml
spring.liquibase.contexts=${spring.profiles.active}

## Hibernate Search - Lucene indexing
spring.jpa.properties.hibernate.search.default.directory_provider=filesystem
spring.jpa.properties.hibernate.search.default.indexBase=./data/lucene

server.servlet.contextPath=/api

merchant.settings.url=${MERCHANT_SETTINGS_URL}
service.images.url=${SERVICE_IMAGES_URL}
spring.servlet.multipart.enabled=true
spring.http.multipart.max-file-size=10MB
spring.http.multipart.max-request-size=11MB