server:
  port: 9090
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: products
          uri: http://localhost:8080
          predicates:
            - Path=/api/products/**
          filters:
            - RewritePath=/api/products/(?<segment>.*), /api/$\{segment}

        - id: merchants
          uri: http://localhost:8070
          predicates:
            - Path=/api/merchants/**
          filters:
            - RewritePath=/api/merchants/(?<segment>.*), /api/$\{segment}