-- BATCH 1
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='20UD0012BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='brand' and pf."filter"='Lenovo')),
                                                                          ((select p.id from products p where code_id='SMN-00009'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='15 инча')),
                                                                          ((select p.id from products p where code_id='SMN-00009'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='512 GB SSD M.2')),
                                                                          ((select p.id from products p where code_id='20S1S1F500'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram' and pf."filter"='40 GB')),
                                                                          ((select p.id from products p where code_id='20S1S1F500'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='SMG-00009'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='256 GB SSD M.2')),
                                                                          ((select p.id from products p where code_id='SMG-00009'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='15 инча')),
                                                                          ((select p.id from products p where code_id='20TA0033BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='Integrated Video')),
                                                                          ((select p.id from products p where code_id='20TA0033BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20S0000UBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='Integrated Video'));

-- BATCH 2
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='20S0000UBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='82TF0006BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram' and pf."filter"='24 GB')),
                                                                          ((select p.id from products p where code_id='82TF0006BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='21BV0078BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='Integrated Video')),
                                                                          ((select p.id from products p where code_id='21BV0078BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='20UJ0010BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='brand' and pf."filter"='Lenovo')),
                                                                          ((select p.id from products p where code_id='20UJ0010BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='6X8Z0EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='NVIDIA GeForce MX')),
                                                                          ((select p.id from products p where code_id='6X8Z0EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='21AH008LBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='NVIDIA GeForce MX'));

-- BATCH 3
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='21AH008LBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20UJ0019BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='brand' and pf."filter"='Lenovo')),
                                                                          ((select p.id from products p where code_id='20UJ0019BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='21BV006YBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='NVIDIA GeForce MX')),
                                                                          ((select p.id from products p where code_id='21BV006YBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='20TD003RBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='NVIDIA GeForce MX')),
                                                                          ((select p.id from products p where code_id='MKGP3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='512 GB SSD')),
                                                                          ((select p.id from products p where code_id='82RG00BUBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='20TD002LBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='NVIDIA GeForce MX')),
                                                                          ((select p.id from products p where code_id='81M9006GBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram' and pf."filter"='4 GB'));

-- BATCH 4
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='82SC0076BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='MGN63ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='256 GB SSD')),
                                                                          ((select p.id from products p where code_id='82UU002LBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='5V8-00009'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='15 инча')),
                                                                          ((select p.id from products p where code_id='20YM002TBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='MNEQ3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='512 GB SSD')),
                                                                          ((select p.id from products p where code_id='20Y5001UBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='82SK006QBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='21E6004RBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='NVIDIA GeForce MX')),
                                                                          ((select p.id from products p where code_id='21K-00010'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram' and pf."filter"='4 GB'));

-- BATCH 5
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='82SV000QBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='21CB005UBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20W000NYBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='82QF001PRM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='MLY13ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='256 GB SSD')),
                                                                          ((select p.id from products p where code_id='MNWA3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='1 TB SSD')),
                                                                          ((select p.id from products p where code_id='MNWD3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='1 TB SSD')),
                                                                          ((select p.id from products p where code_id='20X100QABM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='MKGR3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='512 GB SSD')),
                                                                          ((select p.id from products p where code_id='20W000X2BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча'));

-- BATCH 6
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='20W00094BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20W0009XBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20W000X5BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='21DM000GBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20WE0030BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='82R90007BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='MYD82ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='256 GB SSD')),
                                                                          ((select p.id from products p where code_id='MLY43ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='512 GB SSD')),
                                                                          ((select p.id from products p where code_id='MPHE3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='512 GB SSD')),
                                                                          ((select p.id from products p where code_id='82SV000NBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча'));

-- BATCH 7
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='MNEP3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='256 GB SSD')),
                                                                          ((select p.id from products p where code_id='21CB007JBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='21A00056BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20T60030BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='82QE000BBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='21CB001GBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20T6005SBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20VX00E9BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='MK1A3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='1 TB SSD')),
                                                                          ((select p.id from products p where code_id='82KT004SBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча'));

-- BATCH 8
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='6F5S4EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='6F5W9EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='20UB002UBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='6F5S9EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20TA0027BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20QT000LBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='brand' and pf."filter"='Lenovo')),
                                                                          ((select p.id from products p where code_id='5P749EA#ABB'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='NX.VTWEX.004'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='NX.VTWEX.004'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='512 GB SSD M.2')),
                                                                          ((select p.id from products p where code_id='21D8000KBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='Intel Iris Xe Graphics'));

-- BATCH 9
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='MLXX3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='512 GB SSD')),
                                                                          ((select p.id from products p where code_id='82SC0077BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='6X8Z3EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='NVIDIA GeForce MX')),
                                                                          ((select p.id from products p where code_id='21CF0030BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='MYD92ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='512 GB SSD')),
                                                                          ((select p.id from products p where code_id='21AK0001BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='MPHK3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='1 TB SSD')),
                                                                          ((select p.id from products p where code_id='82RG00BYBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='82RA0005BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='21A0004KBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча'));

-- BATCH 10
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='21CB006PBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20TA002GBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='MNWE3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='1 TB SSD')),
                                                                          ((select p.id from products p where code_id='VFY:U7411MF5CRBA'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='21E3005GBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='21A90007BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='Intel UHD')),
                                                                          ((select p.id from products p where code_id='82SC0078BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='15 инча')),
                                                                          ((select p.id from products p where code_id='20W400HYBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='NVIDIA GeForce MX')),
                                                                          ((select p.id from products p where code_id='6B877EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='82QE0006BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча'));

-- BATCH 11
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='RIQ-00032'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='512 GB SSD')),
                                                                          ((select p.id from products p where code_id='MPHH3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='82RG00BXBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='20WM009QBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='20U5004KBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='RDZ-00008'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='15 инча')),
                                                                          ((select p.id from products p where code_id='20XF001ABM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='6A2A9EA#ABB'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='NVIDIA GeForce MX')),
                                                                          ((select p.id from products p where code_id='MK1H3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='1 TB SSD')),
                                                                          ((select p.id from products p where code_id='MNEJ3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='512 GB SSD'));

-- BATCH 12
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='5Y3T3EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='NVIDIA GeForce MX')),
                                                                          ((select p.id from products p where code_id='82SA00BWBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='16 инча')),
                                                                          ((select p.id from products p where code_id='20XW005JBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='82UU002QBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='5IF-00032'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='15 инча')),
                                                                          ((select p.id from products p where code_id='20TA0024BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='21AH0037BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='14 инча')),
                                                                          ((select p.id from products p where code_id='SKY-00009'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='256 GB SSD')),
                                                                          ((select p.id from products p where code_id='MYDA2ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='256 GB SSD')),
                                                                          ((select p.id from products p where code_id='5Y3T5EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and pf."filter"='NVIDIA GeForce MX'));

-- BATCH 13
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select p.id from products p where code_id='RDZ-00029'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and pf."filter"='15 инча')),
                                                                          ((select p.id from products p where code_id='MLXW3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and pf."filter"='256 GB SSD')),
                                                                          ((select id from products where code_id='MLY23ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='512 GB SSD')),
                                                                          ((select id from products where code_id='MGN93ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='256 GB SSD')),
                                                                          ((select id from products where code_id='MYDC2ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='512 GB SSD')),
                                                                          ((select id from products where code_id='MKGT3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='1 TB SSD')),
                                                                          ((select id from products where code_id='MLY03ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='512 GB SSD')),
                                                                          ((select id from products where code_id='MK183ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='512 GB SSD')),
                                                                          ((select id from products where code_id='MPHF3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='1 TB SSD')),
                                                                          ((select id from products where code_id='MNW83ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='512 GB SSD'));

-- BATCH 14
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='MLXY3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='256 GB SSD')),
                                                                          ((select id from products where code_id='MK1F3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='1 TB SSD')),
                                                                          ((select id from products where code_id='MNEH3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='256 GB SSD')),
                                                                          ((select id from products where code_id='MLY33ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='256 GB SSD')),
                                                                          ((select id from products where code_id='MPHJ3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='1 TB SSD')),
                                                                          ((select id from products where code_id='MK1E3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='512 GB SSD')),
                                                                          ((select id from products where code_id='MNWC3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='512 GB SSD')),
                                                                          ((select id from products where code_id='MNW93ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='1 TB SSD')),
                                                                          ((select id from products where code_id='MGND3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='256 GB SSD')),
                                                                          ((select id from products where code_id='MPHG3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='1 TB SSD'));

-- BATCH 15
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='MKGQ3ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='1 TB SSD')),
                                                                          ((select id from products where code_id='MK193ZE/A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='1 TB SSD')),
                                                                          ((select id from products where code_id='SKR-00009'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='256 GB SSD')),
                                                                          ((select id from products where code_id='21DE001KBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='21BV00A7BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='20T6006DBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20U90009BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20NE000EPB'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20W0012MBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21CB006BBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 16
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='20W0012XBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20UD003VBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21CD0031BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82RG00DHBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='6X8Y8EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82JQ008UBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='20TA000ABM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='5P741EA#ABB'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='20XY0041BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82SC005RBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча'));

-- BATCH 17
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='82LU001RBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='358V3EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82QE000EBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20XW0050BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82RF003MBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='20W000NXBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='6F1W6EA#ABB'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='5IF-00009'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='15 инча')),
                                                                          ((select id from products where code_id='20W000X6BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20VF0009BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 18
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='20UD001BBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20SLA06KBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21AK000FBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82QF001MRM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='6X8Y7EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20UB002SBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82SE000JBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20YM002WBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='21C1003DBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20U9005BBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 19
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='20XW008BBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='VFY:U7411MP7FRBA'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20XK0012BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82SE0009BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='6F6E3EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20UD0013BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='6F5S8EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='358U3EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20WM00AHBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82RF003KBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча'));

-- BATCH 20
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='6X8Y9EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20XW006PBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20VF0007BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20TA002ABM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='15 инча')),
                                                                          ((select id from products where code_id='21AH0082BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20VD0093BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21C1003RBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82LU001UBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='5P720EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20YM002UBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча'));

-- BATCH 21
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='NX.ACWEX.005'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21BV009TBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='21DM0008BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21CF0038BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82RG00DDBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='20WE0021BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='5UI-00025'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='15 инча')),
                                                                          ((select id from products where code_id='20XWS0FL00'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21C5001EBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20U90006BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 22
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='20UN002MBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='13 инча')),
                                                                          ((select id from products where code_id='21CB007FBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21CB005VBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='VFY:E5411MF5FRBA'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21C5001DBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='6X8Y6EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='6F5S3EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20UD0042BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20XW007XBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21E30060BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 23
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='82SK006XBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='21A00043BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21C10041BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20T6002VBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20U1004RBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20X100PSBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21AH0030BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21CH002KBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='82LU001SBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82H700LTBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 24
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='21BV0027BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='82UH002QBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='5P741EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='21A200A9BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='62V28EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='20XY004CBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20XK000MBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21AH007VBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20U90008BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20T6006MBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 25
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='20W000X4BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='597T6EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82LU001TBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='V4G-00008'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='15 инча')),
                                                                          ((select id from products where code_id='82UH002PBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='82SE000EBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20WE0031BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20VD000BBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20W0013KBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21AH00CWBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 26
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='21CD005EBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82SE0005BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21C5001FBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20Y70044BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21CH002EBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='20U9000ABM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21CB005YBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20U1004TBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82QE000JBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20X100PWBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 27
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='3G2P0EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82QF003RBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20W000PCBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82SE0004BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20W0009QBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20X100NVBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20WE0002BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82UU002WBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21CH002FBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='20WMS11U00'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 28
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='PLT-00008'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='15 инча')),
                                                                          ((select id from products where code_id='21E30052BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82SD000BBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20UH001ABM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21BV009YBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='20U50038BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82R70091BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='82SA00BXBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='20U90003BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20XY003UBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 29
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='20W000X1BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20XW0055BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20TA00F7BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='VGZ-00029'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='15 инча')),
                                                                          ((select id from products where code_id='20WE0000BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20TA002JBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20W000TKBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20UN002UBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='13 инча')),
                                                                          ((select id from products where code_id='5P749EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='20S0S2XM00'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 30
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='5P755EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20UES2040A'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='62U06EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='20U5004HBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='336D4EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='15 инча')),
                                                                          ((select id from products where code_id='21C1002YBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21CH0027BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='16 инча')),
                                                                          ((select id from products where code_id='VFY:E5411MF5GRBA'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='20Y700AHBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча')),
                                                                          ((select id from products where code_id='21E30066BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='screen-laptops' and "filter"='14 инча'));

-- BATCH 31 - Video Cards
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='6X8Z6EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='20TD002PBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='5Y3T5EA#ABB'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce RTX')),
                                                                          ((select id from products where code_id='21D80006BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA Quadro')),
                                                                          ((select id from products where code_id='6X8Z5EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='6X8Z4EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='6X900EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='20TD002MBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='6X8Z2EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='5Y3T3EA#ABB'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX'));

-- BATCH 32
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='20S60025BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='21A9000SBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA Quadro')),
                                                                          ((select id from products where code_id='20VE0053BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='20S6002BBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='21A9000BBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA Quadro')),
                                                                          ((select id from products where code_id='20TD003PBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='20W4008WBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='20VE0045BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='20VE00LFBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='20YQ001NBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA Quadro'));

-- BATCH 33
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
                                                                          ((select id from products where code_id='5Y3T8EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='6A2A9EA#AKS'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='video-card' and "filter"='NVIDIA GeForce MX')),
                                                                          ((select id from products where code_id='20LNS1TL00'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram' and "filter"='4 GB')),
                                                                          ((select id from products where code_id='82H802U2BM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram' and "filter"='12 GB')),
                                                                          ((select id from products where code_id='20YRS7VQ00'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram' and "filter"='64 GB')),
                                                                          ((select id from products where code_id='NX.A8XEX.006'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram' and "filter"='4 GB')),
                                                                          ((select id from products where code_id='21K-00009'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram' and "filter"='4 GB')),
                                                                          ((select id from products where code_id='1ZP-00009'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram' and "filter"='4 GB')),
                                                                          ((select id from products where code_id='1ZO-00025'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram' and "filter"='4 GB')),
                                                                          ((select id from products where code_id='NX.AYCEX.00F'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory' and "filter"='1 TB SSD'));

-- BATCH 34 - Final
INSERT INTO products_product_filters (product_id, product_filters_id) VALUES
    ((select id from products where code_id='21BX000WBM'),(select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='processor' and "filter"='Intel Celeron'));
