INSERT INTO product_filters ("filter", group_filters_id, orders)
VALUES
    ('UniSoc', (select id from group_filters where alias='processor-tab'), 15),
    ('Exynos', (select id from group_filters where alias='processor-tab'), 16),
    ('Snapdragon', (select id from group_filters where alias='processor-tab'), 17),
    ('Helio', (select id from group_filters where alias='processor-tab'), 18);


INSERT INTO products_product_filters (product_id, product_filters_id)
VALUES
    ((select id from products where code_id='MK7R3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='MLWL3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='MK2N3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='6 GB')),
    ((select id from products where code_id='TFZ-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='128 GB')),
    ((select id from products where code_id='TND-00009'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='MK8E3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='8PQ-00006'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='VDV-00018'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='128 GB')),
    ((select id from products where code_id='PVR-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='20R5000KBM'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='MPQC3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='6 GB')),
    ((select id from products where code_id='1GF-00017'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='128 GB')),
    ((select id from products where code_id='PVR-00018'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='MK2P3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='6 GB')),
    ((select id from products where code_id='QIX-00021'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='PVR-00020'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='STQ-00017'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='128 GB')),
    ((select id from products where code_id='PVS-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='PVS-00005'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='TGF-00017'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='64 GB')),
    ((select id from products where code_id='MK2L3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='MK7P3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='MQ6U3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='6 GB')),
    ((select id from products where code_id='8VA-00007'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='128 GB')),
    ((select id from products where code_id='8VA-00006'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='128 GB')),
    ((select id from products where code_id='8PQ-00022'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='ZA5H0050BG'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='brand-tab' and pf."filter"='Lenovo')),
    ((select id from products where code_id='MPQA3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='6 GB')),
    ((select id from products where code_id='STV-00016'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='64 GB')),
    ((select id from products where code_id='MPQ23HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='SUA-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='128 GB')),
    ((select id from products where code_id='VFY:U9X11MF7BRBA'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='MK8C3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='TGF-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='64 GB')),
    ((select id from products where code_id='MPQ83HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='6 GB')),
    ((select id from products where code_id='PVR-00005'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='RRX-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='64 GB')),
    ((select id from products where code_id='MK4E3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='6 GB')),
    ((select id from products where code_id='MK493HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='PVT-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='PVT-00005'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='QIX-00007'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='MQ6W3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='6 GB')),
    ((select id from products where code_id='1FS-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='64 GB')),
    ((select id from products where code_id='EFI-00005'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='32 GB')),
    ((select id from products where code_id='PVT-00019'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='SKW-00023'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='MQ6V3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='6 GB')),
    ((select id from products where code_id='ZA3V0009BG'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='brand-tab' and pf."filter"='Lenovo')),
    ((select id from products where code_id='SKW-00024'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='RRX-00017'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='64 GB')),
    ((select id from products where code_id='MPQ93HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='6 GB')),
    ((select id from products where code_id='EHL-00004'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='128 GB')),
    ((select id from products where code_id='MPQ33HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='VFY:U9X11MF5BRBA'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='PVU-00019'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='A1Y-00023'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='1ND-00005'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='MQ6J3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='EFH-00006'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='32 GB')),
    ((select id from products where code_id='8PT-00006'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='THR-00009'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='MK7M3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='EFI-00020'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='32 GB')),
    ((select id from products where code_id='SUF-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='128 GB')),
    ((select id from products where code_id='V6F-00023'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='RW8-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='8VC-00007'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='128 GB')),
    ((select id from products where code_id='MQ6T3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='6 GB')),
    ((select id from products where code_id='MLX43HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='MK893HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='8VH-00017'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='128 GB')),
    ((select id from products where code_id='E7F-00007'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='8VA-00022'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='128 GB')),
    ((select id from products where code_id='MQ6K3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='V6F-00009'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='1NA-00005'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='QI9-00024'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='QEZ-00024'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='MK4H3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='6 GB')),
    ((select id from products where code_id='NNB-00002'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='MPQ13HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='8PX-00006'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='MPQ03HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='MQ6L3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='8V6-00007'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='64 GB')),
    ((select id from products where code_id='MK2K3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='QEZ-00007'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='SLK-00009'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='32 GB')),
    ((select id from products where code_id='MK473HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB')),
    ((select id from products where code_id='SUG-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='256 GB')),
    ((select id from products where code_id='QKV-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='SLZ-00009'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='16 GB')),
    ((select id from products where code_id='SLK-00023'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='32 GB')),
    ((select id from products where code_id='STZ-00003'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='memory-tab' and pf."filter"='64 GB')),
    ((select id from products where code_id='MQ6M3HC/A'), (select pf.id from product_filters pf inner join group_filters gf on pf.group_filters_id = gf.id where gf.alias='ram-tab' and pf."filter"='4 GB'));

INSERT INTO products_product_filters (product_id, product_filters_id)
VALUES
    ((select id from products where code_id='SM-T545NZKAE37'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='Exynos')),
    ((select id from products where code_id='SM-P613NZAABGL'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='Snapdragon')),
    ((select id from products where code_id='SM-T225NZSAEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='Helio')),
    ((select id from products where code_id='SM-X205NZSAEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='UniSoc')),
    ((select id from products where code_id='SM-X205NIDAEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='UniSoc')),
    ((select id from products where code_id='SM-T575NZKAEEE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='Exynos')),
    ((select id from products where code_id='SM-T509NZAAEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='Snapdragon')),
    ((select id from products where code_id='SM-X205NIDEEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='UniSoc')),
    ((select id from products where code_id='SM-T220NZSAEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='Helio')),
    ((select id from products where code_id='SM-T220NZAAEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='Helio')),
    ((select id from products where code_id='SM-X205NZAEEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='UniSoc')),
    ((select id from products where code_id='SM-X200NIDEEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='UniSoc')),
    ((select id from products where code_id='SM-T545NZKABGL'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='Exynos')),
    ((select id from products where code_id='SM-X200NZSAEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='UniSoc')),
    ((select id from products where code_id='SM-X200NZAAEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='UniSoc')),
    ((select id from products where code_id='SM-X205NZAAEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='UniSoc')),
    ((select id from products where code_id='SM-T225NZAAEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='Helio')),
    ((select id from products where code_id='SM-X200NZAEEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='UniSoc')),
    ((select id from products where code_id='SM-X205NZSEEUE'), (select pf.id from product_filters pf join group_filters gf on pf.group_filters_id=gf.id where gf.alias='processor-tab' and pf."filter"='UniSoc'));