user  nginx;
worker_processes  1;
events {
  worker_connections  1024;
}

http {
  include /etc/nginx/mime.types;
  server {
    listen 80;

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2|woff|ttf|eot)$ {
        root /web/build;
        # Set cache duration to one year (31,536,000 seconds)
        expires 31536000s;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        root /web/build/;
        index index.html;

        try_files $uri /index.html;
    }

    location /products-service {
          proxy_pass http://10.100.207.72:9090;
    }

    location /merchants-service {
          proxy_pass http://10.100.207.72:9090;
    }

    location /finance-service {
          proxy_pass http://10.100.207.72:9090;
    }
  }
}