spring.application.name=FINANCE
profiles.active=prod
server.servlet.contextPath=/api
server.port=8080
management.server.port=8090
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
loki.url=${LOKI_URL}