spring.application.name=FINANCE
server.port=9091
management.server.port=8091
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

server.servlet.contextPath=/api

spring.datasource.url=jdbc:postgresql://localhost:5435/finance
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true