spring.application.name=FINANCE
profiles.active=prod
server.servlet.contextPath=/api

server.port=8080
management.server.port=8090
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus,health,info

# Database & Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.datasource.schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.mvc.async.request-timeout=30000
loki.url=${LOKI_URL}

logging.pattern.level=%5p [${spring.application.name:},%X{trace_id},%X{span_id}]
otel.instrumentation.logback-appender.enabled=true