package com.merchants.core.productsettings;

import com.merchants.repositories.productsettings.UrlProductImportSettingsEntity;
import com.merchants.rest.urlimportproductsettings.UrlProductImportSettingsAllDto;
import com.merchants.rest.urlimportproductsettings.UrlProductImportSettingsDto;
import com.merchants.rest.urlimportproductsettings.UrlProductImportSettingsPersistDto;
import com.merchants.rest.urlimportproductsettings.UrlProductImportSettingsUpdateDto;
import org.mapstruct.Mapper;

import java.util.List;

@Mapper(
        componentModel = "spring"
)
public interface UrlProductImportSettingsMapper {
    UrlProductImportSettingsEntity urlProductImportSettingsToUrlProductImportSettingsEntity(UrlProductImportSettings urlProductImportSettings);

    UrlProductImportSettingsDto urlProductImportSettingsToUrlProductImportSettingsDto(UrlProductImportSettings urlProductImportSettings);

    UrlProductImportSettings urlProductImportSettingsDtoToUrlProductImportSettings(UrlProductImportSettingsPersistDto urlProductImportSettingsDto);

    UrlProductImportSettings urlProductImportSettingsDtoToUrlProductImportSettings(UrlProductImportSettingsUpdateDto urlProductImportSettingsDto);

    UrlProductImportSettings urlProductImportSettingsEntityToUrlProductImportSettings(UrlProductImportSettingsEntity urlProductImportSettingsEntity);
    List<UrlProductImportSettings> urlProductImportSettingsEntityToUrlProductImportSettings(List<UrlProductImportSettingsEntity> urlProductImportSettingsEntity);
    List<UrlProductImportSettingsDto> urlProductImportSettingsToUrlProductImportSettingsDto(List<UrlProductImportSettings> urlProductImportSettings);
    List<UrlProductImportSettingsAllDto> urlProductImportSettingsToUrlProductImportSettingsAllDto(List<UrlProductImportSettings> urlProductImportSettings);


}
